name: Build image and push to registry

on:
  push:
    branches:
      - master

# TODO WARNING! Using --password via the CLI is insecure. Use --password-stdin.
# TODO WARNING! Your password will be stored unencrypted in /home/runner/.docker/config.json.
env:
  DOCKER_USER: ${{ secrets.DOCKER_USER }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
  DOCKER_REGISTRY: ${{ secrets.DOCKER_REGISTRY }}
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: docker login
        run: |
          docker login -u $DOCKER_USER -p $DOCKER_PASSWORD $DOCKER_REGISTRY
      - name: docker build
        run: |
          docker build . -t $DOCKER_REGISTRY/homepage
      - name: docker push
        run: docker push $DOCKER_REGISTRY/homepage
      
