name: Build image and push to registry

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: docker build
        run: |
          docker build ./src -t registry.konradmelzer.de/homepage
      - name: docker push
        run: push registry.konradmelzer.de/homepage
      
